#loader contenttweaker

#Name: Blood Sweat & Gears Frangible Ores.zs
#Author: PhoePhoe, Pyure/IT3 dev team, Vyraal1/FTB:I team

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
import mods.contenttweaker.IItemRightClick;
import mods.contenttweaker.Commands;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.Material;
import mods.contenttweaker.Part;
import mods.contenttweaker.Color;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;
import mods.contenttweaker.DropTableBuilder;
import mods.contenttweaker.MaterialPart;
import mods.contenttweaker.Block;
import mods.contenttweaker.PartBuilder;
import mods.contenttweaker.MaterialPartData;
import mods.contenttweaker.MaterialPartLocalizedNameSupplier;

var ore_types = ["frangible"] as string[];

var materialList as string[] = [
"Aluminium Ore",
"Antimony Ore",
"Arsenic Ore",
"Beryllium Ore",
"Bismuth Ore",
"Cadmium Ore",
"Caesium Ore",
"Calcium Ore",
"Carbon Ore",
"Chrome Ore",
"Cobalt Ore",
"Copper Ore",
"Gallium Ore",
"Gold Ore",
"Iridium Ore",
"Iron Ore",
"Lead Ore",
"Lithium Ore",
"Magnesium Ore",
"Manganese Ore",
"Molybdenum Ore",
"Neodymium Ore",
"Nickel Ore",
"Niobium Ore",
"Osmium Ore",
"Palladium Ore",
"Platinum Ore",
"Phosphorus Ore",
"Potassium Ore",
"Silicon Ore",
"Silver Ore",
"Sodium Ore",
"Sulfur Ore",
"Tantalum Ore",
"Thorium Ore",
"Tin Ore",
"Titanium Ore",
"Tungsten Ore",
"Uranium Ore",
"Vanadium Ore",
"Yttrium Ore",
"Zinc Ore",
#6x"Almandine",
"Banded Iron",
"Blue Topaz",
"Brown Limonite",
"Calcite",
"Quicklime",
"Cassiterite",
"Chalcopyrite",
"Chromite",
"Cinnabar",
"Coal",
"Cobaltite",
"Cooperite",
"Diamond",
"Emerald",
"Galena",
"Garnierite",
"Green Sapphire",
#6x"Grossular",
#3x"Ilmenite",
"Rutile",
#3x"Bauxite",
#12x"Lazurite",
"Magnesite",
"Magnetite",
"Molybdenite",
"Phosphate",
"Powellite",
"Pyrite",
"Pyrolusite",
#4x"Pyrope",
#3x"RockSalt",
"Ruby",
#3x"Salt",
#4x"Saltpeter",
"Sapphire",
"Scheelite",
"Silicon Dioxide",
#6x"Sodalite",
"Spessartine",
"Sphalerite",
"Stibnite",
"Tanzanite",
"Tetrahedrite",
"Topaz",
"Tungstate",
"Uraninite",
"Uvarovite",
"Wulfenite",
"Yellow Limonite",
"Nether Quartz",
"Certus Quartz",
"Quartzite",
"Graphite",
"Lignite",
"Olivine",
"Opal",
"Amethyst",
#6x"Redstone",
#6x"Lapis",
"Tantalite",
#5x"Apatite",
#3x"Phosphor",
#4x"GarnetRed",
#4x"GarnetYellow",
"Andradite",
"Vinteum",
"Potassium Feldspar",
"Biotite",
"[V]-Magnetite",
"Bastnasite",
"Pentlandite",
"Spodumene",
"Lepidolite",
"Pitchblende",
#8x"Monazite",
"Malachite",
"Barite",
"Wollastonite",
"Kaolinite",
"Naquadah Ore",
"Naquadria Ore",
"Enriched Naquadah Ore",
"Oilsands",
"Rare Earth",
"Tenorite",
"Cuprite",
"Bornite",
"Chalcocite",
"Tennantite",
"Zirconium",
"Bertrandite",
#5x"Electrotine",
"Euclase",
"Huttonite",
"Coffinite",
"Thorite",
"Zircon",
#3x"Psudobrookite",
"Sperrylite",
"Braggite",
"Brannerite",
"Hubnerite",
"Wolframite",
"Ferberite",
"Sheldonite",
"Bowieite",
"Xenotime",
"Gadolinite",
"Fergusonite",
#8x"[Nd]-Monazite",
"Naquadite",
"Naqulinite",
"Naquarrite",
#3x"Xifengite",
#3x"Xilingolite",
#3x"Berryite",
"Bismuthinite",
#4x"Goslarite",
#3x"Uytenbogaardtite",
#3x"Xanthoconite",
#3x"[S]-Skaergaardite",
"[Ir]-Bowieite",
"Lithrage",
"Argite",
"Corundum",
"Natria",
"Ratsbane",
"Cobaltic",
"Eskolaite",
"Aurite",
"Baria",
"Zincite",
"Bismite",
"Antimonate",
"Bromellite",
"Paramontroseite",
"Coltan",
"Lithia",
"Didymium",
"Cadmite",
"Yttria",
"Ceria",
"Lanthana",
"Caesite",
"Molybdite",
"Sheldite",
"Pallas",
"Baddeleyite",
"Thorianite",
"Iridite",
"Columbite",
"Naquoxiite",
"Naquothxa",
"Montroydite",
"Osmiite",
"Quicksilver",
#4x"Glassy"
];

var materialColour as int[] = [
<material:aluminium>.color,
<material:antimony>.color,
<material:arsenic>.color,
<material:beryllium>.color,
<material:bismuth>.color,
<material:cadmium>.color,
<material:caesium>.color,
<material:calcium>.color,
<material:carbon>.color,
<material:chrome>.color,
<material:cobalt>.color,
<material:copper>.color,
<material:gallium>.color,
<material:gold>.color,
<material:iridium>.color,
<material:iron>.color,
<material:lead>.color,
<material:lithium>.color,
<material:magnesium>.color,
<material:manganese>.color,
<material:molybdenum>.color,
<material:neodymium>.color,
<material:nickel>.color,
<material:niobium>.color,
<material:osmium>.color,
<material:palladium>.color,
<material:platinum>.color,
<material:phosphorus>.color,
<material:potassium>.color,
<material:silicon>.color,
<material:silver>.color,
<material:sodium>.color,
<material:sulfur>.color,
<material:tantalum>.color,
<material:thorium>.color,
<material:tin>.color,
<material:titanium>.color,
<material:tungsten>.color,
<material:uranium>.color,
<material:vanadium>.color,
<material:yttrium>.color,
<material:zinc>.color,
#6x<material:almandine>.color,
<material:banded_iron>.color,
<material:blue_topaz>.color,
<material:brown_limonite>.color,
<material:calcite>.color,
<material:quicklime>.color,
<material:cassiterite>.color,
<material:chalcopyrite>.color,
<material:chromite>.color,
<material:cinnabar>.color,
<material:coal>.color,
<material:cobaltite>.color,
<material:cooperite>.color,
<material:diamond>.color,
<material:emerald>.color,
<material:galena>.color,
<material:garnierite>.color,
<material:green_sapphire>.color,
#6x<material:grossular>.color,
#3x<material:ilmenite>.color,
<material:rutile>.color,
#3x<material:bauxite>.color,
#6x<material:lazurite>.color,
<material:magnesite>.color,
<material:magnetite>.color,
<material:molybdenite>.color,
<material:phosphate>.color,
<material:powellite>.color,
<material:pyrite>.color,
<material:pyrolusite>.color,
#4x<material:pyrope>.color,
#3x<material:rock_salt>.color,
<material:ruby>.color,
#3x<material:salt>.color,
#4x<material:saltpeter>.color,
<material:sapphire>.color,
<material:scheelite>.color,
<material:silicon_dioxide>.color,
#6x<material:sodalite>.color,
<material:spessartine>.color,
<material:sphalerite>.color,
<material:stibnite>.color,
<material:tanzanite>.color,
<material:tetrahedrite>.color,
<material:topaz>.color,
<material:tungstate>.color,
<material:uraninite>.color,
<material:uvarovite>.color,
<material:wulfenite>.color,
<material:yellow_limonite>.color,
<material:nether_quartz>.color,
<material:certus_quartz>.color,
<material:quartzite>.color,
<material:graphite>.color,
<material:lignite>.color,
<material:olivine>.color,
<material:opal>.color,
<material:amethyst>.color,
#6x<material:redstone>.color,
#6x<material:lapis>.color,
<material:tantalite>.color,
#5x<material:apatite>.color,
#3x<material:phosphor>.color,
#4x<material:garnet_red>.color,
#4x<material:garnet_yellow>.color,
<material:andradite>.color,
<material:vinteum>.color,
<material:potassium_feldspar>.color,
<material:biotite>.color,
<material:vanadium_magnetite>.color,
<material:bastnasite>.color,
<material:pentlandite>.color,
<material:spodumene>.color,
<material:lepidolite>.color,
<material:pitchblende>.color,
#8x<material:monazite>.color,
<material:malachite>.color,
<material:barite>.color,
<material:wollastonite>.color,
<material:kaolinite>.color,
<material:naquadah>.color,
<material:naquadria>.color,
<material:naquadah_enriched>.color,
<material:oilsands>.color,
<material:rare_earth>.color,
<material:tenorite>.color,
<material:cuprite>.color,
<material:bornite>.color,
<material:chalcocite>.color,
<material:tennantite>.color,
<material:zirconium>.color,
<material:bertrandite>.color,
#5x<material:electrotine>.color,
<material:euclase>.color,
<material:huttonite>.color,
<material:coffinite>.color,
<material:thorite>.color,
<material:zircon>.color,
#3x<material:psudobrookite>.color,
<material:sperrylite>.color,
<material:braggite>.color,
<material:brannerite>.color,
<material:hubnerite>.color,
<material:wolframite>.color,
<material:ferberite>.color,
<material:sheldonite>.color,
<material:bowieite>.color,
<material:xenotime>.color,
<material:gadolinite>.color,
<material:fergusonite>.color,
#8x<material:monazite_nd>.color,
<material:naquadite>.color,
<material:naqulinite>.color,
<material:naquarrite>.color,
#3x<material:xifengite>.color,
#3x<material:xilingolite>.color,
#3x<material:berryite>.color,
<material:bismuthinite>.color,
#4x<material:goslarite>.color,
#3x<material:uytenbogaardtite>.color,
#3x<material:xanthoconite>.color,
#3x<material:skaergaardite_s>.color,
<material:bowieite_ir>.color,
<material:lithrage>.color,
<material:argite>.color,
<material:corundum>.color,
<material:natria>.color,
<material:ratsbane>.color,
<material:cobaltic>.color,
<material:eskolaite>.color,
<material:aurite>.color,
<material:baria>.color,
<material:zincite>.color,
<material:bismite>.color,
<material:antimonate>.color,
<material:bromellite>.color,
<material:paramontroseite>.color,
<material:coltan>.color,
<material:lithia>.color,
<material:didymium>.color,
<material:cadmite>.color,
<material:yttria>.color,
<material:ceria>.color,
<material:lanthana>.color,
<material:caesite>.color,
<material:molybdite>.color,
<material:sheldite>.color,
<material:pallas>.color,
<material:baddeleyite>.color,
<material:thorianite>.color,
<material:iridite>.color,
<material:columbite>.color,
<material:naquoxiite>.color,
<material:naquothxa>.color,
<material:montroydite>.color,
<material:osmiite>.color,
<material:quicksilver>.color,
#4x<material:glassy>.color
];

var firstByproduct as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Arsenic", //Arsenic
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"GarnetRed", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"Malachite", //BrownLimonite,
"Andradite", //Calcite,
"Calcite", //Quicklime,
"Tin", //Cassiterite,
"Pyrite", //Chalcopyrite,
"Iron", //Chromite,
"Redstone", //Cinnabar,
"Coal", //Coal,
"Nickel", //Cobaltite,
"Palladium", //Cooperite,
"Diamond", //Diamond,
"Beryllium", //Emerald,
"Sulfur", //Galena,
"Nickel", //Garnierite,
"Aluminium", //GreenSapphire,
#6x"GarnetYellow", //Grossular,
#3x"Iron", //Ilmenite,
"Bauxite", //Rutile,
#3x"Grossular", //Bauxite,
#6x"Sodalite", //Lazurite,
"Magnesium", //Magnesite,
"Iron", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Molybdenite", //Powellite,
"Sulfur", //Pyrite,
"Manganese", //Pyrolusite,
#4x"GarnetRed", //Pyrope,
#3x"Salt", //RockSalt,
"Redstone", //Ruby,
#3x"RockSalt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Aluminium", //Sapphire,
"Manganese", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Lazurite", //Sodalite,
"GarnetRed", //Spessartine,
"GarnetYellow", //Sphalerite,
"Antimony", //Stibnite,
"Opal", //Tanzanite,
"Antimony", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Pyrolusite", //Tungstate,
"Uranium", //Uraninite,
"GarnetYellow", //Uvarovite,
"Molybdenite", //Wulfenite,
"Nickel", //YellowLimonite,
"Gold", //NetherQuartz,
"Gold", //CertusQuartz,
"Gold", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Pyrope", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"Cinnabar", //Redstone,
#6x"Lazurite", //Lapis,
"Pyrolusite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Apatite", //Phosphor,
#4x"Spessartine", //GarnetRed,
#4x"Andradite", //GarnetYellow,
"Calcite", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"Gold", //VanadiumMagnetite,
"Neodymium", //Bastnasite,
"Iron", //Pentlandite,
"Aluminium", //Spodumene,
"Lithium", //Lepidolite,
"Thorium", //Pitchblende,
#8x"Thorium", //Monazite,
"Copper", //Malachite,
"Baria", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadah", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Iron", //Tenorite,
"Iron", //Cuprite,
"Pyrite", //Bornite,
"Sulfur", //Chalcocite,
"Iron", //Tennantite,
"Zirconium", //Zirconium,
"Emerald", //Bertrandite,
#5x"Sapphire", //Electrotine,
"Emerald", //Euclase,
"Thorite", //Huttonite,
"Huttonite", //Coffinite,
"Uraninite", //Thorite,
"Baddeleyite", //Zircon,
#3x"Rutile", //Psudobrookite,
"Palladium", //Sperrylite,
"Sheldite", //Braggite,
"Rutile", //Brannerite,
"Iron", //Hubnerite,
"Lithium", //Wolframite,
"Manganese", //Ferberite,
"Sheldite", //Sheldonite,
"Iridite", //Bowieite,
"RareEarth", //Xenotime,
"Iron", //Gadolinite,
"RareEarth", //Fergusonite,
#8x"Didymium", //MonaziteNd,
"Naquoxiite", //Naquadite,
"Iron", //Naqulinite,
"Nickel", //Naquarrite,
#3x"Naquothxa", //Xifengite,
#3x"Naquarrite", //Xilingolite,
#3x"Silver", //Berryite,
"Lead", //Bismuthinite,
#4x"Uvarovite", //Goslarite,
#3x"SkaergaarditeS", //Uytenbogaardtite,
#3x"Sheldite", //Xanthoconite,
#3x"Uytenbogaardtite", //SkaergaarditeS,
"Osmiite", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"Aluminium", //Corundum,
"Sodium", //Natria,
"Arsenic", //Ratsbane,
"Cobalt", //Cobaltic,
"Chrome", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Bismuth", //Bismite,
"Antimony", //Antimonate,
"Beryllium", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalum", //Coltan,
"Lithium", //Lithia,
"RareEarth", //Didymium,
"Cadmium", //Cadmite,
"Yttrium", //Yttria,
"RareEarth", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zirconium", //Baddeleyite,
"Thorium", //Thorianite,
"Iridium", //Iridite,
"Niobium", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Cinnabar", //Montroydite,
"Osmium", //Osmiite,
"Quicksilver", //Quicksilver
#4x"Glassy" //Glassy
	];

var secondByproduct as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Arsenic", //Arsenic
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"Aluminium", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"YellowLimonite", //BrownLimonite,
"Quicklime", //Calcite,
"Calcite", //Quicklime,
"Iron", //Cassiterite,
"Cobalt", //Chalcopyrite,
"Magnesium", //Chromite,
"Sulfur", //Cinnabar,
"Coal", //Coal,
"Cobalt", //Cobaltite,
"Nickel", //Cooperite,
"Diamond", //Diamond,
"Aluminium", //Emerald,
"Silver", //Galena,
"Cobalt", //Garnierite,
"Sapphire", //GreenSapphire,
#6x"Calcium", //Grossular,
#3x"Rutile", //Ilmenite,
"Psudobrookite", //Rutile,
#3x"Rutile", //Bauxite,
#6x"Lapis", //Lazurite,
"Magnesium", //Magnesite,
"Gold", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Calcite", //Powellite,
"Phosphor", //Pyrite,
"Tantalite", //Pyrolusite,
#4x"Almandine", //Pyrope,
#3x"Borax", //RockSalt,
"GarnetRed", //Ruby,
#3x"Borax", //Salt,
#4x"Saltpeter", //Saltpeter,
"GreenSapphire", //Sapphire,
"Molybdenum", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Lapis", //Sodalite,
"Manganese", //Spessartine,
"Cadmium", //Sphalerite,
"Tetrahedrite", //Stibnite,
"Opal", //Tanzanite,
"Zinc", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Silver", //Tungstate,
"Thorium", //Uraninite,
"Uvarovite", //Uvarovite,
"Lead", //Wulfenite,
"BrownLimonite", //YellowLimonite,
"Quartzite", //NetherQuartz,
"NetherQuartz", //CertusQuartz,
"CertusQuartz", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Magnesite", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"RareEarth", //Redstone,
#6x"Sodalite", //Lapis,
"Tantalite", //Tantalite,
#5x"Phosphor", //Apatite,
#3x"Phosphate", //Phosphor,
#4x"Pyrope", //GarnetRed,
#4x"Grossular", //GarnetYellow,
"GarnetYellow", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"Magnetite", //VanadiumMagnetite,
"RareEarth", //Bastnasite,
"Sulfur", //Pentlandite,
"Lithia", //Spodumene,
"Caesium", //Lepidolite,
"Uranium", //Pitchblende,
#8x"Neodymium", //Monazite,
"BrownLimonite", //Malachite,
"Sulfur", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadria", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Manganese", //Tenorite,
"Antimony", //Cuprite,
"Cobalt", //Bornite,
"Lead", //Chalcocite,
"Antimony", //Tennantite,
"Zirconium", //Zirconium,
"Euclase", //Bertrandite,
#5x"Cinnabar", //Electrotine,
"Bertrandite", //Euclase,
"Lead", //Huttonite,
"Uraninite", //Coffinite,
"Coffinite", //Thorite,
"Zircon", //Zircon,
#3x"Bauxite", //Psudobrookite,
"Arsenic", //Sperrylite,
"Pallas", //Braggite,
"Lead", //Brannerite,
"Tungstate", //Hubnerite,
"Tungstate", //Wolframite,
"Tungstate", //Ferberite,
"Nickel", //Sheldonite,
"Platinum", //Bowieite,
"Phosphate", //Xenotime,
"RareEarth", //Gadolinite,
"Neodymium", //Fergusonite,
#8x"Phosphate", //MonaziteNd,
"SiliconDioxide", //Naquadite,
"Naquadite", //Naqulinite,
"Naquothxa", //Naquarrite,
#3x"Iron", //Xifengite,
#3x"Naqulinite", //Xilingolite,
#3x"Lead", //Berryite,
"Silver", //Bismuthinite,
#4x"Cadmite", //Goslarite,
#3x"Sheldite", //Uytenbogaardtite,
#3x"Platinum", //Xanthoconite,
#3x"Pallas", //SkaergaarditeS,
"Platinum", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"GreenSapphire", //Corundum,
"Sodium", //Natria,
"Arsenic", //Ratsbane,
"Garnierite", //Cobaltic,
"Ruby", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Berryite", //Bismite,
"Antimony", //Antimonate,
"Beryllium", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalite", //Coltan,
"Lithium", //Lithia,
"Neodymium", //Didymium,
"RareEarth", //Cadmite,
"RareEarth", //Yttria,
"RareEarth", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zircon", //Baddeleyite,
"Thorium", //Thorianite,
"Iridium", //Iridite,
"RareEarth", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Redstone", //Montroydite,
"Osmium", //Osmiite,
"Quicksilver", //Quicksilver
#4x"Glassy" //Glassy
	];

var thirdByproduct as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Arsenic", //Arsenic
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"GarnetRed", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"Malachite", //BrownLimonite,
"Andradite", //Calcite,
"Calcite", //Quicklime,
"Tin", //Cassiterite,
"Gold", //Chalcopyrite,
"Iron", //Chromite,
"Montroydite", //Cinnabar,
"Coal", //Coal,
"Ratsbane", //Cobaltite,
"Iridium", //Cooperite,
"Diamond", //Diamond,
"Beryllium", //Emerald,
"Lead", //Galena,
"Nickel", //Garnierite,
"Aluminium", //GreenSapphire,
#6x"GarnetYellow", //Grossular,
#3x"Iron", //Ilmenite,
"Aluminium", //Rutile,
#3x"Gallium", //Bauxite,
#6x"Sodalite", //Lazurite,
"Magnesium", //Magnesite,
"BandedIron", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Molybdenum", //Powellite,
"Pyrite", //Pyrite,
"Manganese", //Pyrolusite,
#4x"GarnetRed", //Pyrope,
#3x"Salt", //RockSalt,
"Ruby", //Ruby,
#3x"RockSalt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Aluminium", //Sapphire,
"Calcium", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Pyrite", //Sodalite,
"GarnetRed", //Spessartine,
"Gallium", //Sphalerite,
"Cuprite", //Stibnite,
"Opal", //Tanzanite,
"Antimony", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Lithia", //Tungstate,
"Lead", //Uraninite,
"GarnetYellow", //Uvarovite,
"Lithrage", //Wulfenite,
"Cobalt", //YellowLimonite,
"Barite", //NetherQuartz,
"Barite", //CertusQuartz,
"Barite", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Iron", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"Cinnabar", //Redstone,
#6x"Pyrite", //Lapis,
"Pyrolusite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Apatite", //Phosphor,
#4x"Almandine", //GarnetRed,
#4x"Uvarovite", //GarnetYellow,
"Grossular", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"BandedIron", //VanadiumMagnetite,
"RareEarth", //Bastnasite,
"Cobalt", //Pentlandite,
"Lithia", //Spodumene,
"Borax", //Lepidolite,
"Lead", //Pitchblende,
#8x"RareEarth", //Monazite,
"Calcite", //Malachite,
"Barite", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadah", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Malachite", //Tenorite,
"Malachite", //Cuprite,
"Cadmium", //Bornite,
"Silver", //Chalcocite,
"Zinc", //Tennantite,
"Zirconium", //Zirconium,
"Emerald", //Bertrandite,
#5x"RareEarth", //Electrotine,
"Beryllium", //Euclase,
"Coffinite", //Huttonite,
"Lead", //Coffinite,
"Huttonite", //Thorite,
"Uraninite", //Zircon,
#3x"Rutile", //Psudobrookite,
"Platinum", //Sperrylite,
"Garnierite", //Braggite,
"Uraninite", //Brannerite,
"Manganese", //Hubnerite,
"Lithium", //Wolframite,
"Manganese", //Ferberite,
"Iridite", //Sheldonite,
"Sulfur", //Bowieite,
"Yttria", //Xenotime,
"Beryllium", //Gadolinite,
"Yttria", //Fergusonite,
#8x"RareEarth", //MonaziteNd,
"Naquoxiite", //Naquadite,
"Sulfur", //Naqulinite,
"Cobalt", //Naquarrite,
#3x"Naquadite", //Xifengite,
#3x"Bismuth", //Xilingolite,
#3x"Copper", //Berryite,
"Tin", //Bismuthinite,
#4x"Gallium", //Goslarite,
#3x"Sulfur", //Uytenbogaardtite,
#3x"Iridite", //Xanthoconite,
#3x"Bowieite", //SkaergaarditeS,
"Sulfur", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"Sapphire", //Corundum,
"Natria", //Natria,
"Cobaltite", //Ratsbane,
"Cobaltite", //Cobaltic,
"Ruby", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Bismuthinite", //Bismite,
"Copper", //Antimonate,
"Euclase", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalum", //Coltan,
"Lithium", //Lithia,
"Neodymium", //Didymium,
"RareEarth", //Cadmite,
"RareEarth", //Yttria,
"Ceria", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zircon", //Baddeleyite,
"Thorium", //Thorianite,
"Platinum", //Iridite,
"RareEarth", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Redstone", //Montroydite,
"Iridite", //Osmiite,
"Quicksilver", //Quicksilver
#4x"Glassy" //Glassy
	];

var fourthByproduct as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Arsenic", //Arsenic
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"Almandine", //Almandine,
"BandedIron", //BandedIron,
"BlueTopaz", //BlueTopaz,
"BrownLimonite", //BrownLimonite,
"Calcite", //Calcite,
"Quicklime", //Quicklime,
"Cassiterite", //Cassiterite,
"Chalcopyrite", //Chalcopyrite,
"Chromite", //Chromite,
"Cinnabar", //Cinnabar,
"Coal", //Coal,
"Cobaltite", //Cobaltite,
"Cooperite", //Cooperite,
"Diamond", //Diamond,
"Emerald", //Emerald,
"Galena", //Galena,
"Garnierite", //Garnierite,
"GreenSapphire", //GreenSapphire,
#6x"Grossular", //Grossular,
#3x"Ilmenite", //Ilmenite,
"Rutile", //Rutile,
#3x"Bauxite", //Bauxite,
#6x"Lazurite", //Lazurite,
"Magnesite", //Magnesite,
"Magnetite", //Magnetite,
"Molybdenite", //Molybdenite,
"Phosphate", //Phosphate,
"Powellite", //Powellite,
"Pyrite", //Pyrite,
"Pyrolusite", //Pyrolusite,
#4x"Pyrope", //Pyrope,
#3x"RockSalt", //RockSalt,
"Ruby", //Ruby,
#3x"Salt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Sapphire", //Sapphire,
"Scheelite", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Sodalite", //Sodalite,
"Spessartine", //Spessartine,
"Sphalerite", //Sphalerite,
"Stibnite", //Stibnite,
"Tanzanite", //Tanzanite,
"Tetrahedrite", //Tetrahedrite,
"Topaz", //Topaz,
"Tungstate", //Tungstate,
"Uraninite", //Uraninite,
"Uvarovite", //Uvarovite,
"Wulfenite", //Wulfenite,
"YellowLimonite", //YellowLimonite,
"NetherQuartz", //NetherQuartz,
"CertusQuartz", //CertusQuartz,
"Quartzite", //Quartzite,
"Graphite", //Graphite,
"Lignite", //Lignite,
"Olivine", //Olivine,
"Opal", //Opal,
"Amethyst", //Amethyst,
#6x"Redstone", //Redstone,
#6x"Lapis", //Lapis,
"Tantalite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Phosphor", //Phosphor,
#4x"GarnetRed", //GarnetRed,
#4x"GarnetYellow", //GarnetYellow,
"Andradite", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"VanadiumMagnetite", //VanadiumMagnetite,
"Bastnasite", //Bastnasite,
"Pentlandite", //Pentlandite,
"Spodumene", //Spodumene,
"Lepidolite", //Lepidolite,
"Pitchblende", //Pitchblende,
#8x"Monazite", //Monazite,
"Malachite", //Malachite,
"Barite", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"NaquadahEnriched", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Tenorite", //Tenorite,
"Cuprite", //Cuprite,
"Bornite", //Bornite,
"Chalcocite", //Chalcocite,
"Tennantite", //Tennantite,
"Zirconium", //Zirconium,
"Bertrandite", //Bertrandite,
#5x"Electrotine", //Electrotine,
"Euclase", //Euclase,
"Huttonite", //Huttonite,
"Coffinite", //Coffinite,
"Thorite", //Thorite,
"Zircon", //Zircon,
#3x"Psudobrookite", //Psudobrookite,
"Sperrylite", //Sperrylite,
"Braggite", //Braggite,
"Brannerite", //Brannerite,
"Hubnerite", //Hubnerite,
"Wolframite", //Wolframite,
"Ferberite", //Ferberite,
"Sheldonite", //Sheldonite,
"Bowieite", //Bowieite,
"Xenotime", //Xenotime,
"Gadolinite", //Gadolinite,
"Fergusonite", //Fergusonite,
#8x"MonaziteNd", //MonaziteNd,
"Naquadite", //Naquadite,
"Naqulinite", //Naqulinite,
"Naquarrite", //Naquarrite,
#3x"Xifengite", //Xifengite,
#3x"Xilingolite", //Xilingolite,
#3x"Berryite", //Berryite,
"Bismuthinite", //Bismuthinite,
#4x"Goslarite", //Goslarite,
#3x"Uytenbogaardtite", //Uytenbogaardtite,
#3x"Xanthoconite", //Xanthoconite,
#3x"SkaergaarditeS", //SkaergaarditeS,
"BowieiteIr", //BowieiteIr,
"Lithrage", //Lithrage,
"Argite", //Argite,
"Corundum", //Corundum,
"Natria", //Natria,
"Ratsbane", //Ratsbane,
"Cobaltic", //Cobaltic,
"Eskolaite", //Eskolaite,
"Aurite", //Aurite,
"Baria", //Baria,
"Zincite", //Zincite,
"Bismite", //Bismite,
"Antimonate", //Antimonate,
"Bromellite", //Bromellite,
"Paramontroseite", //Paramontroseite,
"Coltan", //Coltan,
"Lithia", //Lithia,
"Didymium", //Didymium,
"Cadmite", //Cadmite,
"Yttria", //Yttria,
"Ceria", //Ceria,
"Lanthana", //Lanthana,
"Caesite", //Caesite,
"Molybdite", //Molybdite,
"Sheldite", //Sheldite,
"Pallas", //Pallas,
"Baddeleyite", //Baddeleyite,
"Thorianite", //Thorianite,
"Iridite", //Iridite,
"Columbite", //Columbite,
"Naquoxiite", //Naquoxiite,
"Naquothxa", //Naquothxa,
"Montroydite", //Montroydite,
"Osmiite", //Osmiite,
"Quicksilver", //Quicksilver
#4x"Glassy" //Glassy
	];

for i, material in materialList {
	mods.contenttweaker.MaterialSystem.getPartBuilder()
		.setName("frangible")
		.setPartType(MaterialSystem.getPartType("ore"))
		.setOreDictName("oreFrangible")
		.build();
	
	var oreDrops = DropTableBuilder.newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
		.addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
		.addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~material, 1, 1)
		.addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~firstByproduct[i], 1, 1)
        .addItem("empty", 1)
		.newSlot()
        .addItem("oredict:crushed"~firstByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~secondByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~secondByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~thirdByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~thirdByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~fourthByproduct[i], 1, 1)
        .addItem("empty", 1)
        .newSlot()
        .addItem("oredict:crushed"~fourthByproduct[i], 1, 1)
        .addItem("empty", 1);

	var part = MaterialSystem.getMaterialBuilder()
		.setName(material)
		.setColor(materialColour[i])
		.build()
	    .registerPart("frangible")
		.getData();
		
        part.addDataValue("variants", "contenttweaker:frangible_gravel");
        part.addDataValue("hardness", "50");
        part.addDataValue("resistance", "5");
        part.addDataValue("harvestTool", "pickaxe");
        part.addDataValue("harvestLevel", "10");
		part.addDataValue("drops", oreDrops);
	
	//var internalName as string = ["contenttweaker.part.frangible."~material];
	
	//mods.contenttweaker.MaterialSystem.getMaterial(material)
		//material.getUnlocalizedName(internalName);
		//game.setLocalization(internalName, materialName[i]);
	 
}



