#priority 10

#Name: Blood Sweat & Gears Global List Ores by Macerator Output.zs
#Author: PhoePhoe, FTB:I dev team


import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;

print("Global List Ores by Macerator Output");

#Modified from the awesome looping script that was modified from FTB interactions.

#=====================
#---Outputs 2x--------
#=====================
global oreInput2 as string[] = [
"Aluminium",
"Antimony",
"Beryllium",
"Bismuth",
"Cadmium",
"Caesium",
"Calcium",
"Carbon",
"Chrome",
"Cobalt",
"Copper",
"Gallium",
"Gold",
"Iridium",
"Iron",
"Lead",
"Lithium",
"Magnesium",
"Manganese",
"Molybdenum",
"Neodymium",
"Nickel",
"Niobium",
"Osmium",
"Palladium",
"Platinum",
"Phosphorus",
"Potassium",
"Silicon",
"Silver",
"Sodium",
"Sulfur",
"Tantalum",
"Thorium",
"Tin",
"Titanium",
"Tungsten",
"Uranium",
"Vanadium",
"Yttrium",
"Zinc",
#6x"Almandine",
"BandedIron",
"BlueTopaz",
"BrownLimonite",
"Calcite",
"Quicklime",
"Cassiterite",
"Chalcopyrite",
"Chromite",
"Cinnabar",
"Coal",
"Cobaltite",
"Cooperite",
"Diamond",
"Emerald",
"Galena",
"Garnierite",
"GreenSapphire",
#6x"Grossular",
"Ilmenite",
"Rutile",
#3x"Bauxite",
#6x"Lazurite",
"Magnesite",
"Magnetite",
"Molybdenite",
"Phosphate",
"Powellite",
"Pyrite",
"Pyrolusite",
#4x"Pyrope",
#3x"RockSalt",
"Ruby",
#3x"Salt",
#4x"Saltpeter",
"Sapphire",
"Scheelite",
"SiliconDioxide",
#6x"Sodalite",
"Spessartine",
"Sphalerite",
"Stibnite",
"Tanzanite",
"Tetrahedrite",
"Topaz",
"Tungstate",
"Uraninite",
"Uvarovite",
"Wulfenite",
"YellowLimonite",
"NetherQuartz",
"CertusQuartz",
"Quartzite",
"Graphite",
"Lignite",
"Olivine",
"Opal",
"Amethyst",
#6x"Redstone",
#6x"Lapis",
"Tantalite",
#5x"Apatite",
#3x"Phosphor",
#4x"GarnetRed",
#4x"GarnetYellow",
"Andradite",
"Vinteum",
"PotassiumFeldspar",
"Biotite",
"VanadiumMagnetite",
"Bastnasite",
"Pentlandite",
"Spodumene",
"Lepidolite",
"Pitchblende",
#8x"Monazite",
"Malachite",
"Barite",
"Wollastonite",
"Kaolinite",
"Naquadah",
"Naquadria",
"NaquadahEnriched",
"Oilsands",
"RareEarth",
"Tenorite",
"Cuprite",
"Bornite",
"Chalcocite",
"Tennantite",
"Zirconium",
"Bertrandite",
#5x"Electrotine",
"Euclase",
"Huttonite",
"Coffinite",
"Thorite",
"Zircon",
"Psudobrookite",
"Sperrylite",
"Braggite",
"Brannerite",
"Hubnerite",
"Wolframite",
"Ferberite",
"Sheldonite",
"Bowieite",
"Xenotime",
"Gadolinite",
"Fergusonite",
#8x"MonaziteNd",
"Naquadite",
"Naqulinite",
"Naquarrite",
"Xifengite",
"Xilingolite",
"Berryite",
"Bismuthinite",
"Goslarite",
"Uytenbogaardtite",
"Xanthoconite",
"SkaergaarditeS",
"BowieiteIr",
"Lithrage",
"Argite",
"Corundum",
"Natria",
"Ratsbane",
"Cobaltic",
"Eskolaite",
"Aurite",
"Baria",
"Zincite",
"Bismite",
"Antimonate",
"Bromellite",
"Paramontroseite",
"Coltan",
"Lithia",
"Didymium",
"Cadmite",
"Yttria",
"Ceria",
"Lanthana",
"Caesite",
"Molybdite",
"Sheldite",
"Pallas",
"Baddeleyite",
"Thorianite",
"Iridite",
"Columbite",
"Naquoxiite",
"Naquothxa",
"Montroydite",
"Osmiite", //Osmiite,
"Quicksilver", //Quicksilver
"Glassy" //Glassy
	];

global firstByproduct2 as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"GarnetRed", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"Malachite", //BrownLimonite,
"Andradite", //Calcite,
"Calcite", //Quicklime,
"Tin", //Cassiterite,
"Pyrite", //Chalcopyrite,
"Iron", //Chromite,
"Redstone", //Cinnabar,
"Coal", //Coal,
"Nickel", //Cobaltite,
"Palladium", //Cooperite,
"Diamond", //Diamond,
"Beryllium", //Emerald,
"Sulfur", //Galena,
"Nickel", //Garnierite,
"Aluminium", //GreenSapphire,
#6x"GarnetYellow", //Grossular,
"Iron", //Ilmenite,
"Bauxite", //Rutile,
#3x"Grossular", //Bauxite,
#6x"Sodalite", //Lazurite,
"Magnesium", //Magnesite,
"Iron", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Molybdenite", //Powellite,
"Sulfur", //Pyrite,
"Manganese", //Pyrolusite,
#4x"GarnetRed", //Pyrope,
#3x"Salt", //RockSalt,
"Redstone", //Ruby,
#3x"RockSalt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Aluminium", //Sapphire,
"Manganese", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Lazurite", //Sodalite,
"GarnetRed", //Spessartine,
"GarnetYellow", //Sphalerite,
"Antimony", //Stibnite,
"Opal", //Tanzanite,
"Antimony", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Pyrolusite", //Tungstate,
"Uranium", //Uraninite,
"GarnetYellow", //Uvarovite,
"Molybdenite", //Wulfenite,
"Nickel", //YellowLimonite,
"Gold", //NetherQuartz,
"Gold", //CertusQuartz,
"Gold", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Pyrope", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"Cinnabar", //Redstone,
#6x"Lazurite", //Lapis,
"Pyrolusite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Apatite", //Phosphor,
#4x"Spessartine", //GarnetRed,
#4x"Andradite", //GarnetYellow,
"Calcite", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"Gold", //VanadiumMagnetite,
"Neodymium", //Bastnasite,
"Iron", //Pentlandite,
"Aluminium", //Spodumene,
"Lithium", //Lepidolite,
"Thorium", //Pitchblende,
#8x"Thorium", //Monazite,
"Copper", //Malachite,
"Baria", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadah", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Iron", //Tenorite,
"Iron", //Cuprite,
"Pyrite", //Bornite,
"Sulfur", //Chalcocite,
"Iron", //Tennantite,
"Zirconium", //Zirconium,
"Emerald", //Bertrandite,
#5x"Sapphire", //Electrotine,
"Emerald", //Euclase,
"Thorite", //Huttonite,
"Huttonite", //Coffinite,
"Uraninite", //Thorite,
"Baddeleyite", //Zircon,
"Rutile", //Psudobrookite,
"Palladium", //Sperrylite,
"Sheldite", //Braggite,
"Rutile", //Brannerite,
"Iron", //Hubnerite,
"Lithium", //Wolframite,
"Manganese", //Ferberite,
"Sheldite", //Sheldonite,
"Iridite", //Bowieite,
"RareEarth", //Xenotime,
"Iron", //Gadolinite,
"RareEarth", //Fergusonite,
#8x"Didymium", //MonaziteNd,
"Naquoxiite", //Naquadite,
"Iron", //Naqulinite,
"Nickel", //Naquarrite,
"Naquothxa", //Xifengite,
"Naquarrite", //Xilingolite,
"Silver", //Berryite,
"Lead", //Bismuthinite,
"Uvarovite", //Goslarite,
"SkaergaarditeS", //Uytenbogaardtite,
"Sheldite", //Xanthoconite,
"Uytenbogaardtite", //SkaergaarditeS,
"Osmiite", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"Aluminium", //Corundum,
"Sodium", //Natria,
"Arsenic", //Ratsbane,
"Cobalt", //Cobaltic,
"Chrome", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Bismuth", //Bismite,
"Antimony", //Antimonate,
"Beryllium", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalum", //Coltan,
"Lithium", //Lithia,
"RareEarth", //Didymium,
"Cadmium", //Cadmite,
"Yttrium", //Yttria,
"RareEarth", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zirconium", //Baddeleyite,
"Thorium", //Thorianite,
"Iridium", //Iridite,
"Niobium", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Cinnabar", //Montroydite,
"Osmium", //Osmiite,
"Quicksilver", //Quicksilver
"Glassy" //Glassy
	];

global secondByproduct2 as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"Aluminium", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"YellowLimonite", //BrownLimonite,
"Quicklime", //Calcite,
"Calcite", //Quicklime,
"Iron", //Cassiterite,
"Cobalt", //Chalcopyrite,
"Magnesium", //Chromite,
"Sulfur", //Cinnabar,
"Coal", //Coal,
"Cobalt", //Cobaltite,
"Nickel", //Cooperite,
"Diamond", //Diamond,
"Aluminium", //Emerald,
"Silver", //Galena,
"Cobalt", //Garnierite,
"Sapphire", //GreenSapphire,
#6x"Calcium", //Grossular,
"Rutile", //Ilmenite,
"Psudobrookite", //Rutile,
#3x"Rutile", //Bauxite,
#6x"Lapis", //Lazurite,
"Magnesium", //Magnesite,
"Gold", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Calcite", //Powellite,
"Phosphor", //Pyrite,
"Tantalite", //Pyrolusite,
#4x"Almandine", //Pyrope,
#3x"Borax", //RockSalt,
"GarnetRed", //Ruby,
#3x"Borax", //Salt,
#4x"Saltpeter", //Saltpeter,
"GreenSapphire", //Sapphire,
"Molybdenum", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Lapis", //Sodalite,
"Manganese", //Spessartine,
"Cadmium", //Sphalerite,
"Tetrahedrite", //Stibnite,
"Opal", //Tanzanite,
"Zinc", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Silver", //Tungstate,
"Thorium", //Uraninite,
"Uvarovite", //Uvarovite,
"Lead", //Wulfenite,
"BrownLimonite", //YellowLimonite,
"Quartzite", //NetherQuartz,
"NetherQuartz", //CertusQuartz,
"CertusQuartz", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Magnesite", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"RareEarth", //Redstone,
#6x"Sodalite", //Lapis,
"Tantalite", //Tantalite,
#5x"Phosphor", //Apatite,
#3x"Phosphate", //Phosphor,
#4x"Pyrope", //GarnetRed,
#4x"Grossular", //GarnetYellow,
"GarnetYellow", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"Magnetite", //VanadiumMagnetite,
"RareEarth", //Bastnasite,
"Sulfur", //Pentlandite,
"Lithia", //Spodumene,
"Caesium", //Lepidolite,
"Uranium", //Pitchblende,
#8x"Neodymium", //Monazite,
"BrownLimonite", //Malachite,
"Sulfur", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadria", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Manganese", //Tenorite,
"Antimony", //Cuprite,
"Cobalt", //Bornite,
"Lead", //Chalcocite,
"Antimony", //Tennantite,
"Zirconium", //Zirconium,
"Euclase", //Bertrandite,
#5x"Cinnabar", //Electrotine,
"Bertrandite", //Euclase,
"Lead", //Huttonite,
"Uraninite", //Coffinite,
"Coffinite", //Thorite,
"Zircon", //Zircon,
"Bauxite", //Psudobrookite,
"Arsenic", //Sperrylite,
"Pallas", //Braggite,
"Lead", //Brannerite,
"Tungstate", //Hubnerite,
"Tungstate", //Wolframite,
"Tungstate", //Ferberite,
"Nickel", //Sheldonite,
"Platinum", //Bowieite,
"Phosphate", //Xenotime,
"RareEarth", //Gadolinite,
"Neodymium", //Fergusonite,
#8x"Phosphate", //MonaziteNd,
"SiliconDioxide", //Naquadite,
"Naquadite", //Naqulinite,
"Naquothxa", //Naquarrite,
"Iron", //Xifengite,
"Naqulinite", //Xilingolite,
"Lead", //Berryite,
"Silver", //Bismuthinite,
"Cadmite", //Goslarite,
"Sheldite", //Uytenbogaardtite,
"Platinum", //Xanthoconite,
"Pallas", //SkaergaarditeS,
"Platinum", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"GreenSapphire", //Corundum,
"Sodium", //Natria,
"Arsenic", //Ratsbane,
"Garnierite", //Cobaltic,
"Ruby", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Berryite", //Bismite,
"Antimony", //Antimonate,
"Beryllium", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalite", //Coltan,
"Lithium", //Lithia,
"Neodymium", //Didymium,
"RareEarth", //Cadmite,
"RareEarth", //Yttria,
"RareEarth", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zircon", //Baddeleyite,
"Thorium", //Thorianite,
"Iridium", //Iridite,
"RareEarth", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Redstone", //Montroydite,
"Osmium", //Osmiite,
"Quicksilver", //Quicksilver
"Glassy" //Glassy
	];

global thirdByproduct2 as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"GarnetRed", //Almandine,
"BandedIron", //BandedIron,
"Topaz", //BlueTopaz,
"Malachite", //BrownLimonite,
"Andradite", //Calcite,
"Calcite", //Quicklime,
"Tin", //Cassiterite,
"Gold", //Chalcopyrite,
"Iron", //Chromite,
"Montroydite", //Cinnabar,
"Coal", //Coal,
"Ratsbane", //Cobaltite,
"Iridium", //Cooperite,
"Diamond", //Diamond,
"Beryllium", //Emerald,
"Lead", //Galena,
"Nickel", //Garnierite,
"Aluminium", //GreenSapphire,
#6x"GarnetYellow", //Grossular,
"Iron", //Ilmenite,
"Aluminium", //Rutile,
#3x"Gallium", //Bauxite,
#6x"Sodalite", //Lazurite,
"Magnesium", //Magnesite,
"BandedIron", //Magnetite,
"Molybdenum", //Molybdenite,
"Phosphorus", //Phosphate,
"Molybdenum", //Powellite,
"Pyrite", //Pyrite,
"Manganese", //Pyrolusite,
#4x"GarnetRed", //Pyrope,
#3x"Salt", //RockSalt,
"Ruby", //Ruby,
#3x"RockSalt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Aluminium", //Sapphire,
"Calcium", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Pyrite", //Sodalite,
"GarnetRed", //Spessartine,
"Gallium", //Sphalerite,
"Cuprite", //Stibnite,
"Opal", //Tanzanite,
"Antimony", //Tetrahedrite,
"BlueTopaz", //Topaz,
"Lithia", //Tungstate,
"Lead", //Uraninite,
"GarnetYellow", //Uvarovite,
"Lithrage", //Wulfenite,
"Cobalt", //YellowLimonite,
"Barite", //NetherQuartz,
"Barite", //CertusQuartz,
"Barite", //Quartzite,
"Graphite", //Graphite,
"Coal", //Lignite,
"Iron", //Olivine,
"Tanzanite", //Opal,
"Amethyst", //Amethyst,
#6x"Cinnabar", //Redstone,
#6x"Pyrite", //Lapis,
"Pyrolusite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Apatite", //Phosphor,
#4x"Almandine", //GarnetRed,
#4x"Uvarovite", //GarnetYellow,
"Grossular", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"BandedIron", //VanadiumMagnetite,
"RareEarth", //Bastnasite,
"Cobalt", //Pentlandite,
"Lithia", //Spodumene,
"Borax", //Lepidolite,
"Lead", //Pitchblende,
#8x"RareEarth", //Monazite,
"Calcite", //Malachite,
"Barite", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"Naquadah", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Malachite", //Tenorite,
"Malachite", //Cuprite,
"Cadmium", //Bornite,
"Silver", //Chalcocite,
"Zinc", //Tennantite,
"Zirconium", //Zirconium,
"Emerald", //Bertrandite,
#5x"RareEarth", //Electrotine,
"Beryllium", //Euclase,
"Coffinite", //Huttonite,
"Lead", //Coffinite,
"Huttonite", //Thorite,
"Uraninite", //Zircon,
"Rutile", //Psudobrookite,
"Platinum", //Sperrylite,
"Garnierite", //Braggite,
"Uraninite", //Brannerite,
"Manganese", //Hubnerite,
"Lithium", //Wolframite,
"Manganese", //Ferberite,
"Iridite", //Sheldonite,
"Sulfur", //Bowieite,
"Yttria", //Xenotime,
"Beryllium", //Gadolinite,
"Yttria", //Fergusonite,
#8x"RareEarth", //MonaziteNd,
"Naquoxiite", //Naquadite,
"Sulfur", //Naqulinite,
"Cobalt", //Naquarrite,
"Naquadite", //Xifengite,
"Bismuth", //Xilingolite,
"Copper", //Berryite,
"Tin", //Bismuthinite,
"Gallium", //Goslarite,
"Sulfur", //Uytenbogaardtite,
"Iridite", //Xanthoconite,
"Bowieite", //SkaergaarditeS,
"Sulfur", //BowieiteIr,
"Lead", //Lithrage,
"Silver", //Argite,
"Sapphire", //Corundum,
"Natria", //Natria,
"Cobaltite", //Ratsbane,
"Cobaltite", //Cobaltic,
"Ruby", //Eskolaite,
"Gold", //Aurite,
"Baria", //Baria,
"Zinc", //Zincite,
"Bismuthinite", //Bismite,
"Copper", //Antimonate,
"Euclase", //Bromellite,
"Vanadium", //Paramontroseite,
"Tantalum", //Coltan,
"Lithium", //Lithia,
"Neodymium", //Didymium,
"RareEarth", //Cadmite,
"RareEarth", //Yttria,
"Ceria", //Ceria,
"Lanthana", //Lanthana,
"Caesium", //Caesite,
"Molybdenum", //Molybdite,
"Platinum", //Sheldite,
"Palladium", //Pallas,
"Zircon", //Baddeleyite,
"Thorium", //Thorianite,
"Platinum", //Iridite,
"RareEarth", //Columbite,
"Naquadah", //Naquoxiite,
"Naquadria", //Naquothxa,
"Redstone", //Montroydite,
"Iridite", //Osmiite,
"Quicksilver", //Quicksilver
"Glassy" //Glassy
	];

global fourthByproduct2 as string[] = [
"Aluminium", //Aluminium,
"Antimony", //Antimony,
"Beryllium", //Beryllium,
"Bismuth", //Bismuth,
"Cadmium", //Cadmium,
"Caesium", //Caesium,
"Calcium", //Calcium,
"Carbon", //Carbon,
"Chrome", //Chrome,
"Cobalt", //Cobalt,
"Copper", //Copper,
"Gallium", //Gallium,
"Gold", //Gold,
"Iridium", //Iridium,
"Iron", //Iron,
"Lead", //Lead,
"Lithium", //Lithium,
"Magnesium", //Magnesium,
"Manganese", //Manganese,
"Molybdenum", //Molybdenum,
"Neodymium", //Neodymium,
"Nickel", //Nickel,
"Niobium", //Niobium,
"Osmium", //Osmium,
"Palladium", //Palladium,
"Platinum", //Platinum,
"Phosphorus", //Phosphorus,
"Potassium", //Potassium,
"Silicon", //Silicon,
"Silver", //Silver,
"Sodium", //Sodium,
"Sulfur", //Sulfur,
"Tantalum", //Tantalum,
"Thorium", //Thorium,
"Tin", //Tin,
"Titanium", //Titanium,
"Tungsten", //Tungsten,
"Uranium", //Uranium,
"Vanadium", //Vanadium,
"Yttrium", //Yttrium,
"Zinc", //Zinc,
#6x"Almandine", //Almandine,
"BandedIron", //BandedIron,
"BlueTopaz", //BlueTopaz,
"BrownLimonite", //BrownLimonite,
"Calcite", //Calcite,
"Quicklime", //Quicklime,
"Cassiterite", //Cassiterite,
"Chalcopyrite", //Chalcopyrite,
"Chromite", //Chromite,
"Cinnabar", //Cinnabar,
"Coal", //Coal,
"Cobaltite", //Cobaltite,
"Cooperite", //Cooperite,
"Diamond", //Diamond,
"Emerald", //Emerald,
"Galena", //Galena,
"Garnierite", //Garnierite,
"GreenSapphire", //GreenSapphire,
#6x"Grossular", //Grossular,
"Ilmenite", //Ilmenite,
"Rutile", //Rutile,
#3x"Bauxite", //Bauxite,
#6x"Lazurite", //Lazurite,
"Magnesite", //Magnesite,
"Magnetite", //Magnetite,
"Molybdenite", //Molybdenite,
"Phosphate", //Phosphate,
"Powellite", //Powellite,
"Pyrite", //Pyrite,
"Pyrolusite", //Pyrolusite,
#4x"Pyrope", //Pyrope,
#3x"RockSalt", //RockSalt,
"Ruby", //Ruby,
#3x"Salt", //Salt,
#4x"Saltpeter", //Saltpeter,
"Sapphire", //Sapphire,
"Scheelite", //Scheelite,
"SiliconDioxide", //SiliconDioxide,
#6x"Sodalite", //Sodalite,
"Spessartine", //Spessartine,
"Sphalerite", //Sphalerite,
"Stibnite", //Stibnite,
"Tanzanite", //Tanzanite,
"Tetrahedrite", //Tetrahedrite,
"Topaz", //Topaz,
"Tungstate", //Tungstate,
"Uraninite", //Uraninite,
"Uvarovite", //Uvarovite,
"Wulfenite", //Wulfenite,
"YellowLimonite", //YellowLimonite,
"NetherQuartz", //NetherQuartz,
"CertusQuartz", //CertusQuartz,
"Quartzite", //Quartzite,
"Graphite", //Graphite,
"Lignite", //Lignite,
"Olivine", //Olivine,
"Opal", //Opal,
"Amethyst", //Amethyst,
#6x"Redstone", //Redstone,
#6x"Lapis", //Lapis,
"Tantalite", //Tantalite,
#5x"Apatite", //Apatite,
#3x"Phosphor", //Phosphor,
#4x"GarnetRed", //GarnetRed,
#4x"GarnetYellow", //GarnetYellow,
"Andradite", //Andradite
"Vinteum", //Vinteum,
"PotassiumFeldspar", //PotassiumFeldspar,
"Biotite", //Biotite,
"VanadiumMagnetite", //VanadiumMagnetite,
"Bastnasite", //Bastnasite,
"Pentlandite", //Pentlandite,
"Spodumene", //Spodumene,
"Lepidolite", //Lepidolite,
"Pitchblende", //Pitchblende,
#8x"Monazite", //Monazite,
"Malachite", //Malachite,
"Barite", //Barite,
"Wollastonite", //Wollastonite,
"Kaolinite", //Kaolinite,
"Naquadah", //Naquadah,
"Naquadria", //Naquadria,
"NaquadahEnriched", //NaquadahEnriched,
"Oilsands", //Oilsands,
"RareEarth", //RareEarth,
"Tenorite", //Tenorite,
"Cuprite", //Cuprite,
"Bornite", //Bornite,
"Chalcocite", //Chalcocite,
"Tennantite", //Tennantite,
"Zirconium", //Zirconium,
"Bertrandite", //Bertrandite,
#5x"Electrotine", //Electrotine,
"Euclase", //Euclase,
"Huttonite", //Huttonite,
"Coffinite", //Coffinite,
"Thorite", //Thorite,
"Zircon", //Zircon,
"Psudobrookite", //Psudobrookite,
"Sperrylite", //Sperrylite,
"Braggite", //Braggite,
"Brannerite", //Brannerite,
"Hubnerite", //Hubnerite,
"Wolframite", //Wolframite,
"Ferberite", //Ferberite,
"Sheldonite", //Sheldonite,
"Bowieite", //Bowieite,
"Xenotime", //Xenotime,
"Gadolinite", //Gadolinite,
"Fergusonite", //Fergusonite,
#8x"MonaziteNd", //MonaziteNd,
"Naquadite", //Naquadite,
"Naqulinite", //Naqulinite,
"Naquarrite", //Naquarrite,
"Xifengite", //Xifengite,
"Xilingolite", //Xilingolite,
"Berryite", //Berryite,
"Bismuthinite", //Bismuthinite,
"Goslarite", //Goslarite,
"Uytenbogaardtite", //Uytenbogaardtite,
"Xanthoconite", //Xanthoconite,
"SkaergaarditeS", //SkaergaarditeS,
"BowieiteIr", //BowieiteIr,
"Lithrage", //Lithrage,
"Argite", //Argite,
"Corundum", //Corundum,
"Natria", //Natria,
"Ratsbane", //Ratsbane,
"Cobaltic", //Cobaltic,
"Eskolaite", //Eskolaite,
"Aurite", //Aurite,
"Baria", //Baria,
"Zincite", //Zincite,
"Bismite", //Bismite,
"Antimonate", //Antimonate,
"Bromellite", //Bromellite,
"Paramontroseite", //Paramontroseite,
"Coltan", //Coltan,
"Lithia", //Lithia,
"Didymium", //Didymium,
"Cadmite", //Cadmite,
"Yttria", //Yttria,
"Ceria", //Ceria,
"Lanthana", //Lanthana,
"Caesite", //Caesite,
"Molybdite", //Molybdite,
"Sheldite", //Sheldite,
"Pallas", //Pallas,
"Baddeleyite", //Baddeleyite,
"Thorianite", //Thorianite,
"Iridite", //Iridite,
"Columbite", //Columbite,
"Naquoxiite", //Naquoxiite,
"Naquothxa", //Naquothxa,
"Montroydite", //Montroydite,
"Osmiite", //Osmiite,
"Quicksilver", //Quicksilver
"Glassy" //Glassy
	];

#=====================
#---Outputs 3x--------
#=====================
global oreInput3 as string[] = [
"Bauxite",
"RockSalt",
"Salt",
"Phosphor"];

global firstByproduct3 as string[] = [
"Grossular", //Bauxite,
"Salt", //RockSalt,
"RockSalt", //Salt,
"Apatite", //Phosphor,
];

global secondByproduct3 as string[] = [
"Rutile", //Bauxite,
"Borax", //RockSalt,
"Borax", //Salt,
"Phosphate", //Phosphor,
	];

global thirdByproduct3 as string[] = [
"Gallium", //Bauxite,
"Salt", //RockSalt,
"RockSalt", //Salt,
"Apatite", //Phosphor,
	];

global fourthByproduct3 as string[] = [
"Bauxite", //Bauxite,
"RockSalt", //RockSalt,
"Salt", //Salt,
"Phosphor", //Phosphor,
	];

#=====================
#---Outputs 4x--------
#=====================
global oreInput4 as string[] = [
"Pyrope",
"Saltpeter",
"GarnetRed",
"GarnetYellow"];

global firstByproduct4 as string[] = [
"GarnetRed", //Pyrope,
"Saltpeter", //Saltpeter,
"Spessartine", //GarnetRed,
"Andradite", //GarnetYellow,
];

global secondByproduct4 as string[] = [
"Almandine", //Pyrope,
"Saltpeter", //Saltpeter,
"Pyrope", //GarnetRed,
"Grossular", //GarnetYellow,
	];

global thirdByproduct4 as string[] = [
"GarnetRed", //Pyrope,
"Saltpeter", //Saltpeter,
"Almandine", //GarnetRed,
"Uvarovite", //GarnetYellow,
	];

global fourthByproduct4 as string[] = [
"Pyrope", //Pyrope,
"Saltpeter", //Saltpeter,
"GarnetRed", //GarnetRed,
"GarnetYellow", //GarnetYellow,
	];

#=====================
#---Outputs 5x--------
#=====================
global oreInput5 as string[] = [
"Apatite",
"Electrotine"
];

global firstByproduct5 as string[] = [
"Apatite", //Apatite,
"Sapphire", //Electrotine,
];

global secondByproduct5 as string[] = [
"Phosphor", //Apatite,
"Cinnabar", //Electrotine,
	];

global thirdByproduct5 as string[] = [
"Apatite", //Apatite,
"RareEarth", //Electrotine,
	];

global fourthByproduct5 as string[] = [
"Apatite", //Apatite,
"Electrotine", //Electrotine,
	];

#=====================
#---Outputs 6x--------
#=====================
global oreInput6 as string[] = [
"Almandine",
"Grossular",
"Lazurite",
"Sodalite",
"Redstone",
"Lapis",
];

global firstByproduct6 as string[] = [
"GarnetRed", //Almandine,
"GarnetYellow", //Grossular,
"Sodalite", //Lazurite,
"Lazurite", //Sodalite,
"Cinnabar", //Redstone,
"Lazurite", //Lapis,
];

global secondByproduct6 as string[] = [
"Aluminium", //Almandine,
"Calcium", //Grossular,
"Lapis", //Lazurite,
"Lapis", //Sodalite,
"RareEarth", //Redstone,
"Sodalite", //Lapis,
	];

global thirdByproduct6 as string[] = [
"GarnetRed", //Almandine,
"GarnetYellow", //Grossular,
"Sodalite", //Lazurite,
"Pyrite", //Sodalite,
"Cinnabar", //Redstone,
"Pyrite", //Lapis,
	];

global fourthByproduct6 as string[] = [
"Almandine", //Almandine,
"Grossular", //Grossular,
"Lazurite", //Lazurite,
"Sodalite", //Sodalite,
"Redstone", //Redstone,
"Lapis", //Lapis,
	];

#=====================
#---Outputs 8x--------
#=====================
global oreInput8 as string[] = [
"Monazite",
"MonaziteNd"];

global firstByproduct8 as string[] = [
"Thorium", //Monazite,
"Didymium", //MonaziteNd,
];

global secondByproduct8 as string[] = [
"Neodymium", //Monazite,
"Phosphate", //MonaziteNd,
	];

global thirdByproduct8 as string[] = [
"RareEarth", //Monazite,
"RareEarth", //MonaziteNd,
	];

global fourthByproduct8 as string[] = [
"Monazite", //Monazite,
"MonaziteNd", //MonaziteNd,
	];



